ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: 7..latest
  - name: firefox
    version: latest
  - name: internet explorer
    version: 10..latest
  - name: android
    version: latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
browserify:
  - transform: babelify
  - options:
      bare: true